### PR TITLE
New 400plus folder

### LINKED ISSUE #111: Add a 400_PLUS folder
```
Add a 400_PLUS folder on the card with all the file we need like presets, user 
guide and so on;

```

Original issue reported on code.google.com by `scri...@gmail.com` on 18 Jul 2011 at 1:34
* Blocking: #304
* Blocked on: #74

### PR DESCRIPTION
**Pull request by eduperez**
Create a new 400PLUS folder on startup, and write our files there. However, users are advised to create the folder themselves, and move all our files but AUTOEXEC.BIN to that folder (this will be documented as the new installation procedure on next release).

Fixes #111.

### CODE REVIEW

**Comment by eduperez** [comment]
Create a new 400PLUS folder on startup, and write our files there. However, users are advised to create the folder themselves, and move all our files but AUTOEXEC.BIN to that folder (this will be documented as the new installation procedure on next release).

Fixes #111.

**Comment by 0xAF** [comment]
Very good!
I'm glad you solved the problem with the folders.
What was the problem actually?
I have pale memory that FIO_CreateDirectory() was not working for unknown reasons?!?
How did you made it work?

**Comment by eduperez** [comment]
Hi there! Glad yo know you are still around here!

I do not remember what was the roadblock for this, or if we ever had one... I recall we could not list files, because he had found opendir but not readdir; that was before the big VXWorks job. Anyway, we didn't need those to create the folders, and FIO_CreateDirectory seems to be working just right.

**Comment by 0xAF** [comment]
Ahh, perhaps my memory was not correct. Anyway, I'm happy to see it done :) Thanks :)

**Comment by eduperez** [comment]
Oh, and I just grabbed the code from one of your test sections... ;)

**Comment by 0xAF** [comment]
Nice, I'm glad it helped...

**Pull request merged**
