### PR TITLE
Move the overlay inside the semaphores and checks in TransferNormalScreen

### PR DESCRIPTION
**Pull request by eduperez**
Instead of printing our overlay **before** calling `TransferNormalScreen`, this change moves the overlay **inside** `TransferNormalScreen`, and after all semaphores have been acquired. If this does not fix the issue with the camera locking, I will disable the overlay.

### CODE REVIEW

**Comment by danieltroger** [comment]
Well, I just <a href="https://leetfil.es/file/76999fee">compiled the changes</a> and am going to test and report issues if I encounter any.

**Comment by danieltroger** [comment]
One freeze so far, although it's already much better than before.
Additionally when I then tried to get out of the freeze the camera looked like this:
image20150606_145438648

**Comment by danieltroger** [comment]
Hm, so, this doesn't work. The second freeze painted some stripes on the screen, the third was just black and so on...

**Comment by 0xAF** [comment]
Yet, the change is good. I vote to leave it there (in the code), but strip out for production.

**Comment by danieltroger** [comment]
Sure, the change is not bad, I just tried to say that it doesn't fix the whole freezing issue what it should do as far as I understood(?)

**Comment by 0xAF** [comment]
Yup, the change was supposed to fix the freezing, as Edu stated in the commit message.
Thanks to you, we now (unfortunately) know it's not fixing the problem.

Anyway, since Edu mentioned, he is going to disable the overlay if the change is not fixing the issue, I decided to add my comment.
Sooner or later, this will be fixed I guess, and by looking the code, this version of overlay is better than the previous. At least the params of the Transfer functions are correct now and it's using the CacheHacks. So, it's better this way, than previous.
That's why I commented the code change.

**Comment by eduperez** [comment]
I was convinced that cause of the problems with the overlay was that we were not respecting the semaphores that the original firmware uses, and this change would fix that. Unfortunately, it seems that we are now writing outside of the display buffer. And I cannot figure out how to fix this.

Until someone discovers how to do the overlay properly, I am going to completely disable it. As I said before, I prefer to have a working BETA, where we can test new features.

**Pull request merged**
