### PR TITLE
Improve shortcuts

### PR DESCRIPTION
**Pull request by eduperez**

### CODE REVIEW

**Comment by 0xAF** [comment]
Just an idea. You should probably record a short video of the new shortcuts. I'm curious to see how it works. :) And it can serve as tutorial for the users. If you have time and the will of course, it's just an idea.

**Comment by eduperez** [comment]
I will obviously have to write some documentation on these shortcuts before doing an official release; the comments here are way too small to make something decent, probably good enough for beta testers, but not for final users.

But I also like your idea of making a small video, I think it will not cost much to make one; I will give it a try tonight, if I have some spare time.

**Comment by Eldurinn** [comment]
The user manual is great, but it would be even better if there was a video outlining all features of 400Plus.  For example, when I was following the manual, I was still having trouble figuring out how the custom modes worked.

**Comment by eduperez** [comment]
Here you are, the new shortcuts in action:
[https://youtu.be/tjQDtYIccW4](url)

**Comment by Eldurinn** [comment]
Those are awesome! I like how they're labeled in the shots remaining box, too. Do you know when this will be released?

**Comment by eduperez** [comment]
Glad to know you like it; but I am afraid there is no schedule here.

**Comment by 0xAF** [comment]
Very nice. Look perfect. Thanks.

**Pull request merged**
