### PR TITLE
VxWorks calls

### PR DESCRIPTION
**Pull request by eduperez**
Large bunch of VxWorks calls: quite probably all libraries included in the current firmware have been found and documented here. There are still a few calls from stdio.h missing, that I will review and document soon; anything else missing here has probably been inlined or excluded by the compiler.

### CODE REVIEW

**Comment by 0xAF** [comment]
That's huge job, you've done Edu.
You've found many addresses and made the structures for most of the functions.
Do you have them mapped in the database file? I would like to see it if so ;)

**Comment by eduperez** [comment]
The binary size is a little larger: I guess the list of .o files included is not stripped out of the final executable; it works, but I want to work on that a little bit before doing the final merging. I also want to finish the transition from the gcc headers to the vxworks headers.

**Comment by 0xAF** [comment]
Thanks for your effort.
BTW, nice trick with: -Wl,--gc-sections
How does it change the size?

**Comment by eduperez** [comment]
According to Our Lord Google, "-fdata-sections -ffunction-sections" separates data and code into different sections, and "-Wl,--gc-sections" discards unused sections (see http://stackoverflow.com/questions/6687630/c-c-gcc-ld-remove-unused-symbols for more info). I just tried that, it reduces the final size in about 2KB, and everything seems to work.

**Comment by 0xAF** [comment]
And what was the size before this merge? Does this option reduced the size to the original size, before the commit? Just curious.

**Comment by eduperez** [comment]
It was 97.904 before adding all those symbols, then it went down to 96.467 [*] while I added the symbols, and now it is at 94.451.

[*] The size went up a few bytes each time I added new symbols that we do not use, and down when added others that replace calls from standard libraries (we do not need to link the  "m" library any longer, for example).

**Comment by 0xAF** [comment]
That's good... I cant remember why we needed the -lm, but it was for just one function IIRC.
Glad to know it's stripped out now.

**Pull request merged**
